### ISSUE TITLE
Reading recharge package fails when time-varying parameters are present

### ISSUE THREAD

**Issue by matejgedeon** [rogiersbart/RMODFLOW#17]
This concerns `rmf_read_rch` in the development branch of cneyens repository. When reading in a complex recharge file, the code fails. I think the subroutine `rmfi_parse_variables` does not read all entries, when INSTANCES are used. Here are the files:

[rch_related_files.zip](https://github.com/rogiersbart/RMODFLOW/files/4379731/rch_related_files.zip)

**Comment by cneyens** [comment]
Apparently, not all instances are saved in `rmfi_parse_array_parameters`. This will also require updating `rmf_create_parameter`. I can have a look this weekend since I won't be going anywhere else...

Note that RMODFLOW has not been tested against time-varying parameters, so even after the fix you might still run into issues.

@rogiersbart you want me to push the fix to your develop branch directly, or rather make separate branch and PR into develop?

**Comment by cneyens** [comment]
This is now fixed on branch [`cneyens:fixes`](https://github.com/cneyens/RMODFLOW/tree/fixes).

**Comment by rogiersbart** [comment]
Which was merged in #14 .
