### ISSUE TITLE
RGDAL Dependency Future

### ISSUE THREAD

**Issue by scantle** [rogiersbart/RMODFLOW#26]
Hey RMODFLOW team,

I'm a big fan of this package. Is there any plan to update it to handle the [recent deprecation of RGDAL](https://r-spatial.org/r/2022/04/12/evolution.html)? The dependency seems to prevent RMODFLOW from being installed on the latest version(s) of R. Thanks!

**Comment by cneyens** [comment]
Hi Leland,

Glad to hear you're using RMODFLOW! I don't know when this will be fixed in the master branch. For now, you can install [the develop branch from my fork](https://github.com/cneyens/RMODFLOW/tree/develop) using: `devtools::install_github("cneyens/RMODFLOW@develop")`

The `rgdal` and `sp` dependencies are removed in that branch. There's also some new stuff, mostly for interpolation, resampling to other grids and exporting to rasters using the [terra](https://rspatial.github.io/terra/) package. The UZF package for MODFLOW is also supported in that branch.

Let me know if this works for you.

**Comment by scantle** [comment]
That's great and works well for me - very excited to try out the new developments. Thanks!

**Comment by scantle** [comment]
That's great and works well for me - very excited to try out the new developments. Thanks!
